# docker-compose.yml
version: '3.5'

services:
  chat-api:
    build: ./
    ports:
      - 8080:8080
    depends_on:
      - postgres
    environment:
      - WAIT_HOSTS=postgres:5432
      - POSTGRES_HOST=postgres

  postgres:
    restart: always
    hostname: postgres
    image: postgres:latest
    volumes:
      - ./schema/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432