# docker-compose.yml
version: '3.5'

services:
  chat-api:
    build: ./
    command: [ "./wait-for-postgres.sh", "db", "./api" ]
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - DB_PASSWORD=password

  db:
    restart: always
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432